version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  node: circleci/node@5.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - node/install:
          node-version: '20.11.1'
      - run:
          name: Generate config
          command: |
            cd .circleci
            ./generate_config
      - continuation/continue:
          configuration_path: build_config.yml
workflows:
  setup:
    jobs:
      - setup