version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
            cd .circleci
            ./generate-config
      - continuation/continue:
          configuration_path: build_config.yml

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - setup