version: 2.1

executors:
  "linux/amd64": # Docker using the Base Convenience Image
    docker:
      - image: docker
  "linux/arm64": # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2204:2024.01.2
    resource_class: arm.medium

commands:
  configure-ghcr:
    description: Configure GHCR access
    steps:
      - run:
          name: Configure GHCR
          command: |
            [ -z "$GHCR_TOKEN" ] && exit 0
            [ -z "$GHCR_USER" ] && exit 0
            echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin
jobs:
    build:
      parameters:
        platform:
          type: executor
      executor: << parameters.platform >>
      steps:
        - checkout
        - configure-ghcr
        - run:
            name: Build
            command: |
              docker buildx bake --set _platforms.platform=<< parameters.platform >> << parameters.target >>
workflows:
  build-all:
    jobs:
      - build:
          context: ghcr-token
          matrix:
            parameters:
              platform: [linux/amd64, linux/arm64]
              target: [proxy, server]

